from tokens import tokens

t_BOOL = r'(true | false)'
t_LEFTARROW = r'<-'
t_GT = r'>'
t_GEQ = r'>='
t_LT = r'<'
t_LEQ = r'<='
t_LPARAN = r'\('
t_RPARAN = r'\)'
t_LSQRB = r'\['
t_RSQRB = r'\]'
t_LCURLYB = r'\{'
t_RCURLYB = r'\}'
t_OP_ADD = r'\+'
t_OP_SUB = r'-'
t_OP_MULT = r'\*'
t_OP_DIVIDE = r'/'
t_OP_MOD = r'%'
t_OP_NOT = r'!'
t_EQ = r'=='
t_NEQ = r'!='
t_AND = r'&&'
t_OR = r'\|\|'
t_XOR = r'\^'
t_LO_AND = '&'
t_LO_OR = '\|'
t_OP_LSHIFT = r'<<'
t_OP_RSHIFT = r'>>'
t_OP_RRSHIFT = r'>>>'
t_EQ_ASGN = r'='
t_ADD_ASGN = r'\+='
t_SUB_ASGN = r'-='
t_MULT_ASGN = r'\*='
t_MOD_ASGN = r'%='
t_DIV_ASGN = r'/='
t_LSHIFT_ASGN = r'<<='
t_RSHIFT_ASGN = r'>>='
t_AND_ASGN = r'&='
t_OR_ASGN = r'\|='
t_XOR_ASGN = r'\^='
t_COLON = r':'
t_SEMI_COLON = r';'
t_DOT = r'\.'
t_COMMA = r'\,'
#t_UNDER = r'_'


# t_ADDASGN = r'\+='
# t_SUBASGN = r'-='
# t_MULASGN = r'\*='
# t_MODASGN = r'%='
# t_DIVASGN = r'/='
# t_LSHIFTASGN = r'<<='
# t_RSHIFTASGN = r'>>='
# t_ANDASGN = r'&='
# t_ORASGN = r'\|='
# t_XORASGN = r'\^='

# t_RRSHIFT = r'>>>'
# t_RSHIFT = r'>>'
# t_LSHIFT = r'<<'

# t_AND = r'&&'
# t_OR = r'\|\|'

# t_LEFTARROW = r'<-'
# t_GE = r'>='
# t_LE = r'<='
# t_GT = r'>'
# t_LT = r'<'
# t_EQ = r'=='
# t_NEQ = r'!='

# t_EQUALASGN = r'='

# t_LPARAN = r'\('
# t_RPARAN = r'\)'
# t_LSQRB = r'\['
# t_RSQRB = r'\]'
# t_BLOCKBEGIN = r'\{'
# t_BLOCKEND = r'\}'

# t_OP_ADD = r'\+'
# t_OP_SUB = r'-'
# t_OP_MUL = r'\*'
# t_OP_DIV = r'/'
# t_OP_MOD = r'%'
# t_OP_NOT = r'!'

# t_XOR = r'\^'
# t_AND_BIT = '&'
# t_OR_BIT = '\|'

# t_COLON = r':'
# t_SEMICOLON = r';'
# t_DOT = r'\.'
# t_COMMA = r'\,'
